version: "3.7"

services:
        ngnix_front-server:
                image: nginx:latest
                ports:
                        - "1235:80"
                volumes:
                        -  './front.conf:/etc/ngnix/nginx.conf'

