version: "3.7"

services:

  node_exporter:
    image: commonregistry646.azurecr.io/nodexporter:v1
    container_name: node_exporter
    restart: unless-stopped
    ports:
    - 9100:9100
              
  cadvisor:
    image: commonregistry646.azurecr.io/cadvisor:v1
    container_name: cadvisor
    restart: unless-stopped
    # expose:
    # - 1234
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
